### ISSUE TITLE
Update AFL

### ISSUE THREAD

**Issue by bannsec** [shellphish/afl-other-arch#1]
There have been some major performance improvements in later AFL releases. What is the process for updating the AFL version that comes in this repo?

**Comment by zardus** [comment]
I think a good start would be swapping out d04ba735110318d42ca646d56d533f9202bfb26d for the new version of the source code.

Long-term, since this repo is intended to be a "normal" AFL, for other architectures, a good solution would be to upstream the changes (@nickstephens!), and get rid of this repo (making `shellphish-afl` just pull the actual AFL source). Not sure how reasonable that is, though...

**Comment by zardus** [comment]
Years later, this can be closed! This repo has been obsoleted by build process updates in `shellphish-afl`.
